# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lifelog}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yutaka HARA"]
  s.date = %q{2009-10-03}
  s.description = %q{A lifelogging tool written in Ramaze}
  s.email = %q{yutaka.hara/at/gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "controller/init.rb",
     "controller/main.rb",
     "layout/default.xhtml",
     "lifelog.gemspec",
     "main.rb",
     "model/init.rb",
     "model/migrations.rb",
     "model/post.rb",
     "model/tag.rb",
     "spec/helper.rb",
     "spec/main.rb",
     "spec/models.rb",
     "view/index.xhtml"
  ]
  s.homepage = %q{http://github.com/yhara/lifelog}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A lifelogging tool written in Ramaze}
  s.test_files = [
    "spec/helper.rb",
     "spec/main.rb",
     "spec/models.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ramaze>, ["= 2009.10"])
      s.add_runtime_dependency(%q<do_sqlite3>, ["= 0.10.0"])
      s.add_runtime_dependency(%q<dm-core>, ["= 0.10.1"])
      s.add_runtime_dependency(%q<dm-validations>, ["= 0.10.1"])
      s.add_runtime_dependency(%q<dm-aggregations>, ["= 0.10.1"])
    else
      s.add_dependency(%q<ramaze>, ["= 2009.10"])
      s.add_dependency(%q<do_sqlite3>, ["= 0.10.0"])
      s.add_dependency(%q<dm-core>, ["= 0.10.1"])
      s.add_dependency(%q<dm-validations>, ["= 0.10.1"])
      s.add_dependency(%q<dm-aggregations>, ["= 0.10.1"])
    end
  else
    s.add_dependency(%q<ramaze>, ["= 2009.10"])
    s.add_dependency(%q<do_sqlite3>, ["= 0.10.0"])
    s.add_dependency(%q<dm-core>, ["= 0.10.1"])
    s.add_dependency(%q<dm-validations>, ["= 0.10.1"])
    s.add_dependency(%q<dm-aggregations>, ["= 0.10.1"])
  end
end
